resolvers:
        - 1.1.1.1
        - 1.0.0.1
        - 8.8.8.8
        - 8.8.4.4
        - 9.9.9.9
        - 9.9.9.10
        - 77.88.8.8
        - 77.88.8.1
        - 208.67.222.222
        - 208.67.220.220
sources:
        - alienvault
        - archiveis
        - binaryedge
        - bufferover
        - censys
        - certspotter
        - certspotterold
        - commoncrawl
        - crtsh
        - digicert
        - dnsdumpster
        - dnsdb
        - entrust
        - googleter
        - hackertarget
        - intelx
        - ipv4info
        - passivetotal
        - rapiddns
        - securitytrails
        - shodan
        - sitedossier
        - sublist3r
        - spyse
        - threatcrowd
        - threatminer
        - urlscan
        - virustotal
        - waybackarchive
        - zoomeye
censys:
        - <key-here>
binaryedge:
        - <key-here>
certspotter:
        - <key-here>
facebook: []
intelx:
        - <public.intelx.io:key-here>
passivetotal:
        - <email:key-here>
securitytrails:
        - <key-here>
urlscan: []
virustotal:
        - <key-here>
chaos:
        - <key-here>
spyse:
        - <key-here>
